import { advantages, certifications, companyProfile, faqs, industrialVisuals, industries, products, services } from "@/data/actotive";
import { CertificateGallery } from "./CertificateGallery";
import { ContactPanel } from "./ContactPanel";
import type { Locale } from "@/data/locale";

export function HomeSections({ locale }: { locale: Locale }) { const tr = locale === "tr"; const translatedIndustries = tr ? [["01", "Demiryolu", "Yük ve demiryolu altyapısı için kritik bileşenler."], ["02", "Lokomotif", "Zorlu operasyonlar için bağımsız satış sonrası destek."], ["03", "Demiryolu Araçları", "Sürekli hizmet için güvenilir yolcu vagonu bileşenleri."], ["04", "Denizcilik", "Deniz filoları için motor ve turboşarj uzmanlığı."]] as const : industries; const translatedProducts = tr ? [{ title: "Lokomotif Yedek Parçaları", copy: "Güç aktarma, frenleme ve yardımcı sistemler", image: products[0].image }, { title: "Turboşarj Bileşenleri", copy: "Güvenilir performans için hassas bileşenler", image: products[1].image }, { title: "Yolcu Vagonu Bileşenleri", copy: "İç mekan, mekanik ve güvenlik sistemleri", image: products[2].image }, { title: "Deniz Motoru Bileşenleri", copy: "Ticari denizcilik operasyonları için parça tedariki", image: products[3].image }, { title: "Yük Taşımacılığı Hizmetleri", copy: "Zaman kritik endüstriyel sevkiyatlar için verimli taşıma", image: products[4].image }] : products; const translatedServices = tr ? ["Teknik Danışmanlık", "Bileşen Tedariği", "Kalite Güvencesi", "Tedarik Zinciri Yönetimi", "Teknik Destek", "Özel Çözümler"] : services; return <>
  <section id="industries" className="section industries"><p className="kicker">02 / {tr ? "Sektörler" : "Industries"}</p><div className="section-heading"><h2>{tr ? "Hareket halindeki" : "Built for the"}<br /><em>{tr ? "dünya için." : "world in motion."}</em></h2><p>{tr ? "Lokomotiflerden deniz motorlarına kadar kritik varlıkları hareket halinde tutan parça ve yetkinlikleri tedarik ediyoruz." : "From locomotives to marine engines, we help operators source the parts and capability that keep critical assets moving."}</p></div><div className="industry-grid">{translatedIndustries.map(([num,title,copy]) => <article key={title}><span>{num}</span><h3>{title}</h3><p>{copy}</p><b>{tr ? "İnceleyin" : "Explore"} <i>↗</i></b></article>)}</div></section>
  <section className="section sourcing-guide"><p className="kicker">{tr ? "Satın alma rehberi" : "Procurement guide"}</p><h2>{tr ? "İhtiyacınızdan doğru çözüme." : "From requirement to the right solution."}</h2><p className="context-links">{tr ? <>Parça talebinizi hazırlamak için <a href="/tr/products">bileşen tedarik rehberimizi</a> inceleyin. Teslimat ve teknik gereksinimler için <a href="/tr/services">mühendislik ve lojistik hizmetlerimizi</a> keşfedin. Satın alma değerlendirmesinde <a href="/tr/quality">kalite belgelerimizi ve DB2 yetkilendirmesini</a> kontrol edin.</> : <>Start with our <a href="/products">railway and marine component sourcing guide</a> to prepare your parts enquiry. Explore <a href="/services">engineering support and freight forwarding</a> to plan technical and delivery requirements. Review our <a href="/quality">quality certificates and DB2 authorization</a> as part of your supplier assessment.</>}</p></section>
  <section id="products" className="section products"><p className="kicker">03 / {tr ? "Ürün kategorileri" : "Product categories"}</p><h2>{tr ? "Parçayı bulun." : "Find the part."}<br /><em>{tr ? "Harekete devam edin." : "Keep moving."}</em></h2><div className="product-grid">{translatedProducts.map(({ title, copy, image },i) => <a href={`${tr ? "/tr" : ""}/${i === 4 ? "services" : "products"}`} key={title}><img src={image} alt={title} loading="lazy" /><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p><i>↗</i></a>)}</div><p className="aftermarket-note">{tr ? "Satış sonrası ürünler OEM spesifikasyonlarını karşılamak veya aşmak üzere tasarlanır. Parça numaraları yalnızca referans amaçlıdır." : companyProfile.aftermarketNotice}</p></section>
  <section className="part-search"><p className="kicker">{tr ? "Parça bulucu" : "Part finder"}</p><h2>{tr ? "Numarayı biliyor musunuz?" : "Know the number?"}<br />{tr ? "Yolu biliyoruz." : "We know the way."}</h2><form><label htmlFor="part">{tr ? "SKU, parça numarası veya açıklama" : "SKU, part number or description"}</label><div><input id="part" placeholder="e.g. 466746-5013" /><button type="submit">{tr ? "Parça ara" : "Search parts"} <span>→</span></button></div></form></section>
  <section id="services" className="section services"><p className="kicker">04 / {tr ? "Mühendislik ve hizmetler" : "Engineering & services"}</p><div className="section-heading"><h2>{tr ? "Tavizsiz" : "Capability without"}<br /><em>{tr ? "yetkinlik." : "compromise."}</em></h2><p>{tr ? "Operasyonunuzun gerçekleriyle uyumlu, bağımsız düşünce ve titiz mühendislik desteği." : "Independent thinking and rigorous engineering support, aligned to the realities of your operation."}</p></div><div className="services-visual"><img src={industrialVisuals.workshop} alt="Locomotive engineering workshop" /></div><ol>{translatedServices.map((service,i) => <li key={service}><span>0{i+1}</span><h3>{service}</h3><i>↗</i></li>)}</ol></section>
  <section className="statement"><p>{tr ? "Mühendislik yaklaşımı" : "Engineering statement"}</p><blockquote>{tr ? "“Yapamazsak," : "“If we can&apos;t make it,"}<br /><em>{tr ? "buluruz.”" : "we'll find it.”"}</em></blockquote></section>
  <section id="about" className="section about"><p className="kicker">05 / About ACTOTIVE</p><div className="section-heading"><h2>Built on<br /><em>operational trust.</em></h2><p>{companyProfile.overview}</p></div><div className="mission-grid"><article><span>Mission</span><p>{companyProfile.mission}</p></article><article><span>Vision</span><p>{companyProfile.vision}</p></article></div><div className="values">{companyProfile.values.map((value, i) => <span key={value}><b>0{i + 1}</b>{value}</span>)}</div></section>
  <section id="network" className="network"><img className="network-visual" src={industrialVisuals.network} alt="Global rail and maritime logistics network" /><div className="network-content"><p className="kicker">06 / {tr ? "Küresel tedarik ağı" : "Global supply network"}</p><h2>{tr ? "Yerel bilgi." : "Local intelligence."}<br /><em>{tr ? "Küresel erişim." : "Global reach."}</em></h2><div className="regions">{(tr ? ["Avrupa","Orta Doğu","Afrika","Asya"] : ["Europe","Middle East","Africa","Asia"]).map((region,i)=><span key={region}><b>0{i+1}</b>{region}</span>)}</div></div></section>
  <section id="quality" className="section why"><p className="kicker">07 / {tr ? "Neden ACTOTIVE" : "Why ACTOTIVE"}</p><h2>{tr ? "Önemli olan yerde" : "Trusted where"}<br /><em>{tr ? "güvenilir." : "it matters."}</em></h2><div>{advantages.map((item,i)=><p key={item}><span>0{i+1}</span>{tr ? (["Küresel Ağ", "Kalite Güvencesi", "Rekabetçi Tedarik", "Güvenilir Lojistik", "Teknik Uzmanlık", "Müşteri Odaklı Çözümler"][i]) : item}</p>)}</div></section>
  <section className="section faq"><p className="kicker">Frequently asked questions</p><div className="section-heading"><h2>Answers for<br /><em>moving operations.</em></h2><p>Clear information for procurement, technical and logistics teams.</p></div><div className="faq-list">{faqs.map(({ question, answer }) => <details key={question}><summary><h3>{question}</h3><span>+</span></summary><p>{answer}</p></details>)}</div></section>
  <section className="certificates section"><p className="kicker">Standards & certifications</p><div className="section-heading"><h2>Evidence you<br /><em>can inspect.</em></h2><p>Our quality, environmental and occupational safety certifications are available to view in full.</p></div><CertificateGallery /></section>
  <section className="authorization"><p className="kicker">Rail freight authorization</p><strong>DB2</strong><p>{companyProfile.authorization}</p></section>
  <section id="contact" className="section contact"><p className="kicker">08 / Contact</p><div className="section-heading"><h2>Talk to the<br /><em>team that moves.</em></h2><p>Tell us the part, requirement or delivery challenge. We will connect you with the right specialist.</p></div><ContactPanel /></section>
  <section id="rfq" className="rfq"><img className="rfq-visual" src={industrialVisuals.rfq} alt="Precision turbocharger components" /><div className="rfq-content"><p className="kicker">07 / Request for quote</p><h2>Let&apos;s put your<br /><em>operation in motion.</em></h2><a className="button primary" href="mailto:sales@actotive.co">Start your RFQ <span>↗</span></a></div></section>
</> }
