import { advantages, certifications, companyProfile, contactDetails, faqs, industrialVisuals, industries, products, services } from "@/data/actotive";
import { CertificateGallery } from "./CertificateGallery";

export function HomeSections() { return <>
  <section id="industries" className="section industries"><p className="kicker">02 / Industries</p><div className="section-heading"><h2>Built for the<br /><em>world in motion.</em></h2><p>From locomotives to marine engines, we help operators source the parts and capability that keep critical assets moving.</p></div><div className="industry-grid">{industries.map(([num,title,copy]) => <article key={title}><span>{num}</span><h3>{title}</h3><p>{copy}</p><b>Explore <i>↗</i></b></article>)}</div></section>
  <section id="products" className="section products"><p className="kicker">03 / Product categories</p><h2>Find the part.<br /><em>Keep moving.</em></h2><div className="product-grid">{products.map(({ title, copy, image },i) => <a href="#rfq" key={title}><img src={image} alt="" /><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p><i>↗</i></a>)}</div><p className="aftermarket-note">{companyProfile.aftermarketNotice}</p></section>
  <section className="part-search"><p className="kicker">Part finder</p><h2>Know the number?<br />We know the way.</h2><form><label htmlFor="part">SKU, part number or description</label><div><input id="part" placeholder="e.g. 466746-5013" /><button type="submit">Search parts <span>→</span></button></div></form></section>
  <section id="services" className="section services"><p className="kicker">04 / Engineering & services</p><div className="section-heading"><h2>Capability without<br /><em>compromise.</em></h2><p>Independent thinking and rigorous engineering support, aligned to the realities of your operation.</p></div><div className="services-visual"><img src={industrialVisuals.workshop} alt="Locomotive engineering workshop" /></div><ol>{services.map((service,i) => <li key={service}><span>0{i+1}</span><h3>{service}</h3><i>↗</i></li>)}</ol></section>
  <section className="statement"><p>Engineering statement</p><blockquote>“If we can&apos;t make it,<br /><em>we&apos;ll find it.</em>”</blockquote></section>
  <section id="about" className="section about"><p className="kicker">05 / About ACTOTIVE</p><div className="section-heading"><h2>Built on<br /><em>operational trust.</em></h2><p>{companyProfile.overview}</p></div><div className="mission-grid"><article><span>Mission</span><p>{companyProfile.mission}</p></article><article><span>Vision</span><p>{companyProfile.vision}</p></article></div><div className="values">{companyProfile.values.map((value, i) => <span key={value}><b>0{i + 1}</b>{value}</span>)}</div></section>
  <section id="network" className="network"><img className="network-visual" src={industrialVisuals.network} alt="Global rail and maritime logistics network" /><div className="network-content"><p className="kicker">06 / Global supply network</p><h2>Local intelligence.<br /><em>Global reach.</em></h2><div className="regions">{["Europe","Middle East","Africa","Asia"].map((region,i)=><span key={region}><b>0{i+1}</b>{region}</span>)}</div></div></section>
  <section id="quality" className="section why"><p className="kicker">06 / Why ACTOTIVE</p><h2>Trusted where<br /><em>it matters.</em></h2><div>{advantages.map((item,i)=><p key={item}><span>0{i+1}</span>{item}</p>)}</div></section>
  <section className="section faq"><p className="kicker">Frequently asked questions</p><div className="section-heading"><h2>Answers for<br /><em>moving operations.</em></h2><p>Clear information for procurement, technical and logistics teams.</p></div><div className="faq-list">{faqs.map(({ question, answer }) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
  <section className="certificates section"><p className="kicker">Standards & certifications</p><div className="section-heading"><h2>Evidence you<br /><em>can inspect.</em></h2><p>Our quality, environmental and occupational safety certifications are available to view in full.</p></div><CertificateGallery /></section>
  <section className="authorization"><p className="kicker">Rail freight authorization</p><strong>DB2</strong><p>{companyProfile.authorization}</p></section>
  <section id="contact" className="section contact"><p className="kicker">08 / Contact</p><div className="section-heading"><h2>Talk to the<br /><em>team that moves.</em></h2><p>Tell us the part, requirement or delivery challenge. We will connect you with the right specialist.</p></div><div className="contact-grid"><a href={contactDetails.phoneHref}><span>Phone</span><strong>{contactDetails.phone}</strong><small>Call center</small></a><a href={contactDetails.whatsappHref} target="_blank" rel="noreferrer"><span>WhatsApp</span><strong>Message us</strong><small>{contactDetails.phone}</small></a><a href={`mailto:${contactDetails.email}`}><span>Email</span><strong>{contactDetails.email}</strong><small>Sales & enquiries</small></a><div><span>Location</span><strong>{contactDetails.location}</strong><small>Global supply network</small></div></div></section>
  <section id="rfq" className="rfq"><img className="rfq-visual" src={industrialVisuals.rfq} alt="Precision turbocharger components" /><div className="rfq-content"><p className="kicker">07 / Request for quote</p><h2>Let&apos;s put your<br /><em>operation in motion.</em></h2><a className="button primary" href="mailto:info@actotive.com">Start your RFQ <span>↗</span></a></div></section>
</> }
